Repository SuperV1234/SSVOpenHexagon, pull requests merged in 2020-09, with the labels that each got.

#273 Get Camera Shake to accept float values
  include/SSVOpenHexagon/Data/LevelData.hpp
  src/SSVOpenHexagon/Core/HGGraphics.cpp
Labels: fix

#285 Fix pack list in main menu shifting horizontally when longest named pack is selected
  src/SSVOpenHexagon/Core/MenuGame.cpp
Labels: fix

#281 onLoad runs when the level starts instead of level initialization
  src/SSVOpenHexagon/Core/HGUpdate.cpp
  src/SSVOpenHexagon/Core/HexagonGame.cpp
Labels: fix

#284 Lua function to edit the player movement speed
  include/SSVOpenHexagon/Core/HexagonGame.hpp
  include/SSVOpenHexagon/Data/LevelData.hpp
  src/SSVOpenHexagon/Components/CPlayer.cpp
  src/SSVOpenHexagon/Core/HGScripting.cpp
  src/SSVOpenHexagon/Core/HexagonGame.cpp
  src/SSVOpenHexagon/Core/MenuGame.cpp
Labels: lua function

#278 Allow Pack Developers to Override the Timer for Alternative Scoring
  include/SSVOpenHexagon/Core/HGStatus.hpp
  include/SSVOpenHexagon/Core/HexagonGame.hpp
  include/SSVOpenHexagon/Core/Replay.hpp
  include/SSVOpenHexagon/Data/LevelData.hpp
  src/SSVOpenHexagon/Core/HGGraphics.cpp
  src/SSVOpenHexagon/Core/HGScripting.cpp
  src/SSVOpenHexagon/Core/HGStatus.cpp
  src/SSVOpenHexagon/Core/HGUpdate.cpp
  src/SSVOpenHexagon/Core/HexagonGame.cpp
  src/SSVOpenHexagon/Core/MenuGame.cpp
  src/SSVOpenHexagon/Core/Replay.cpp
  test/Replay.t.cpp
Labels: enhancement, lua function

#254 Improve utils.lua with new math functions and useful enumerators
  _RELEASE/Packs/cube/Scripts/Levels/apeirogon.lua
  _RELEASE/Packs/cube/Scripts/Levels/babysteps.lua
  _RELEASE/Packs/cube/Scripts/Levels/euclideanpc.lua
  _RELEASE/Packs/cube/Scripts/Levels/flatteringshape.lua
  _RELEASE/Packs/cube/Scripts/Levels/goldenratio.lua
  _RELEASE/Packs/cube/Scripts/Levels/pi.lua
  _RELEASE/Packs/cube/Scripts/Levels/pointless.lua
  _RELEASE/Packs/cube/Scripts/Levels/seconddimension.lua
  _RELEASE/Packs/cube/Scripts/utils.lua
  _RELEASE/Packs/experimental/Scripts/Levels/3D_required.lua
  _RELEASE/Packs/experimental/Scripts/Levels/arcadia.lua
  _RELEASE/Packs/experimental/Scripts/Levels/cw.lua
  _RELEASE/Packs/experimental/Scripts/Levels/negative_pulse.lua
  _RELEASE/Packs/experimental/Scripts/utils.lua
  _RELEASE/Packs/hypercube/Scripts/Levels/acceleradiant.lua
  _RELEASE/Packs/hypercube/Scripts/Levels/disc-o.lua
  _RELEASE/Packs/hypercube/Scripts/Levels/evotutorial.lua
  _RELEASE/Packs/hypercube/Scripts/Levels/g-force.lua
  _RELEASE/Packs/hypercube/Scripts/Levels/incongruence.lua
  _RELEASE/Packs/hypercube/Scripts/Levels/massacre.lua
  _RELEASE/Packs/hypercube/Scripts/Levels/polyhedrug.lua
  _RELEASE/Packs/hypercube/Scripts/Levels/reppaws.lua
  _RELEASE/Packs/hypercube/Scripts/Levels/slither.lua
  _RELEASE/Packs/hypercube/Scripts/utils.lua
  _RELEASE/Packs/workshopexample/Scripts/Levels/examplelevel.lua
  _RELEASE/Packs/workshopexample/Scripts/utils.lua
  _RELEASE/Temp/example/Scripts/Levels/examplelevel.lua
Labels: enhancement

#289 Fix onUnload's priority
  include/SSVOpenHexagon/Core/HexagonGame.hpp
  include/SSVOpenHexagon/Core/Replay.hpp
  src/SSVOpenHexagon/Core/HexagonGame.cpp
  src/SSVOpenHexagon/Core/Replay.cpp
  test/Replay.t.cpp
Labels: fix

#291 Keyboard bind menu item bugfix
  src/SSVOpenHexagon/Global/Config.cpp
Labels: fix

#293 The Sound Update
  _RELEASE/Assets/Open Hexagon Assets License.txt
  _RELEASE/Assets/assets.json
  _RELEASE/Assets/beep.ogg
  _RELEASE/Assets/death.ogg
  _RELEASE/Assets/error.ogg
  _RELEASE/Assets/increment.ogg
  _RELEASE/Assets/restart.ogg
  _RELEASE/Assets/select.ogg
  _RELEASE/Assets/swap.ogg
  src/SSVOpenHexagon/Core/HexagonDialogBox.cpp
  src/SSVOpenHexagon/Core/HexagonGame.cpp
  src/SSVOpenHexagon/Core/MenuGame.cpp
Labels: enhancement

#294 Bind controls beta testers suggestions
  _RELEASE/config.json
  include/SSVOpenHexagon/Core/BindControl.hpp
  include/SSVOpenHexagon/Core/MenuGame.hpp
  include/SSVOpenHexagon/Global/Config.hpp
  include/SSVOpenHexagon/Global/UtilsJson.hpp
  misc/default_config.json
  src/SSVOpenHexagon/Core/BindControl.cpp
  src/SSVOpenHexagon/Core/HexagonGame.cpp
  src/SSVOpenHexagon/Core/MenuGame.cpp
  src/SSVOpenHexagon/Global/Config.cpp
Labels: fix
