Repository SuperV1234/SSVOpenHexagon, pull requests merged in 2020-07, with the labels that each got.

#216 New lua style function `s_setColorOffset(`
  include/SSVOpenHexagon/Data/StyleData.hpp
  src/SSVOpenHexagon/Core/HGGraphics.cpp
  src/SSVOpenHexagon/Core/HGScripting.cpp
  src/SSVOpenHexagon/Core/MenuGame.cpp
  src/SSVOpenHexagon/Data/StyleData.cpp
Labels: feature

#217 New lua function `BGTileRadius`
  include/SSVOpenHexagon/Data/StyleData.hpp
  src/SSVOpenHexagon/Core/HGScripting.cpp
  src/SSVOpenHexagon/Core/MenuGame.cpp
  src/SSVOpenHexagon/Data/StyleData.cpp
Labels: lua function

#218 New lua function for style `BGRotationOffset`
  include/SSVOpenHexagon/Data/StyleData.hpp
  src/SSVOpenHexagon/Core/HGScripting.cpp
  src/SSVOpenHexagon/Core/MenuGame.cpp
  src/SSVOpenHexagon/Data/StyleData.cpp
Labels: lua function

#213 Added a force swap lua function for the player `u_swapPlayer()`.
  include/SSVOpenHexagon/Components/CPlayer.hpp
  src/SSVOpenHexagon/Components/CPlayer.cpp
  src/SSVOpenHexagon/Core/HGScripting.cpp
Labels: lua function

#224 Fix Mouse Hide through config.
  src/SSVOpenHexagon/Core/MenuGame.cpp
  src/SSVOpenHexagon/Core/main.cpp
  src/SSVOpenHexagon/Global/Config.cpp
Labels: fix

#222 Enhancement/203 create build script || Enhancement/220 setup to run on debian systems
  .gitignore
  README.md
  build.sh
  build/car.sh
  build/car_debug.sh
  build/car_uploader.sh
  build/cmake_mingw_debug.sh
  build/cmake_mingw_release.sh
  buildlx/car.sh
  buildlx/car_debug.sh
  buildlx/car_valgrind.sh
Labels: enhancement

#226 Feature/221 show difficulty multiplier on steam and discord
  include/SSVOpenHexagon/Core/Discord.hpp
  include/SSVOpenHexagon/Core/Steam.hpp
  misc/richpresence.txt
  src/SSVOpenHexagon/Core/Discord.cpp
  src/SSVOpenHexagon/Core/HGUpdate.cpp
  src/SSVOpenHexagon/Core/Steam.cpp
Labels: feature

#230 Bugfix/227 fix current time on steam not updating
  include/SSVOpenHexagon/Core/HexagonGame.hpp
  src/SSVOpenHexagon/Core/HGUpdate.cpp
  src/SSVOpenHexagon/Core/HexagonGame.cpp
Labels: bug, fix

#238 WIP Replay System
  CMakeLists.txt
  _RELEASE/Assets/assets.json
  _RELEASE/Assets/replayIcon.png
  _RELEASE/Packs/cube/Scripts/Levels/euclideanpc.lua
  _RELEASE/config.json
  art/replayicon.psd
  build/car.sh
  build/car_debug.sh
  include/SSVOpenHexagon/Core/HGStatus.hpp
  include/SSVOpenHexagon/Core/HexagonGame.hpp
  include/SSVOpenHexagon/Core/RandomNumberGenerator.hpp
  include/SSVOpenHexagon/Core/Replay.hpp
  include/SSVOpenHexagon/Global/Config.hpp
  include/SSVOpenHexagon/Utils/Utils.hpp
  misc/default_config.json
  src/SSVOpenHexagon/Components/CPlayer.cpp
  src/SSVOpenHexagon/Core/HGGraphics.cpp
  src/SSVOpenHexagon/Core/HGScripting.cpp
  src/SSVOpenHexagon/Core/HGUpdate.cpp
  src/SSVOpenHexagon/Core/HexagonGame.cpp
  src/SSVOpenHexagon/Core/MenuGame.cpp
  src/SSVOpenHexagon/Core/RandomNumberGenerator.cpp
  src/SSVOpenHexagon/Core/Replay.cpp
  src/SSVOpenHexagon/Global/Config.cpp
  test/CMakeLists.txt
  test/Replay.t.cpp
  test/TestUtils.hpp
Labels: feature

#239 Recoded collisions.
  _RELEASE/Packs/cube/Scripts/Levels/goldenratio.lua
  _RELEASE/Packs/experimental/Levels/curvetest.json
  _RELEASE/Packs/experimental/Scripts/Levels/curvetest.lua
  _RELEASE/Packs/hypercube/Scripts/evolutionpatterns.lua
  include/SSVOpenHexagon/Components/CPlayer.hpp
  include/SSVOpenHexagon/Components/CWall.hpp
  include/SSVOpenHexagon/Core/HexagonGame.hpp
  src/SSVOpenHexagon/Components/CPlayer.cpp
  src/SSVOpenHexagon/Components/CWall.cpp
  src/SSVOpenHexagon/Core/HGUpdate.cpp
Labels: enhancement

#255 Add silent message function to menu Lua
  src/SSVOpenHexagon/Core/MenuGame.cpp
Labels: fix
